### ISSUE TITLE
Integrate CI service

### ISSUE THREAD

**Issue by jeanleonino** [EnLab/webrtc-backend#1]

**Comment by AwolDes** [comment]
Not sure if you wanted me to actually upload and fully integrate the CI myself, but I rekcon we should use [Travis CI for node](http://docs.travis-ci.com/user/languages/javascript-with-nodejs/) or [Circle CI](https://circleci.com/features) but CircleCI isn't free

**Comment by jeanleonino** [comment]
Travis is free only for open source. Circle has 30 days free at least, and uses containers. Feels faster than Travis somehow bc of it (you create and destroy the environment everytime, on Travis you share resources).

**Comment by AwolDes** [comment]
Alright, I've never used a CI before so you'd know better than I would when it comes to this

**Comment by jeanleonino** [comment]
@wesy2kn1 it's up to you

**Comment by wesy2kn1** [comment]
I vote Travis @jeanleonino

**Comment by jeanleonino** [comment]
:+1:
