### ISSUE TITLE
Use a js linter

### ISSUE THREAD

**Issue by jeanleonino** [EnLab/webrtc-backend#3]
Set up and put to work a JS Linter, like jshint.

**Comment by AwolDes** [comment]
Checked out both [Jslint](http://www.jslint.com/) and [Jshint](http://jshint.com/) and read [this](http://stackoverflow.com/questions/6803305/should-i-use-jslint-or-jshint-javascript-validation) as a comparison and I think Jslint is the better option for us.

**Comment by jeanleonino** [comment]
Agreed.
